environment: development

apphost: k8s

label:
  name: backendk8s

container:
  name: backendk8s
  pullPolicy: IfNotPresent
  image: backend
  tag: v1
  port: 80
replicas: 3

service:
  port: 8888
  type: ClusterIP
